const playersData = [
    {
        "id": 1,
        "name": "TenZ",
        "team": "sentinels",
        "region": "na",
        "agents": ["Omen", "KAY/O", "Gekko"],
        "roles": ["Controller", "Initiator"],
        "sensitivity": "0.175 @ 1600 DPI",
        "crosshair": "0;s;1;P;c;5;h;0;m;1;0l;4;0o;2;0a;1;0t;2;0f;0;1b;0;S;c;5;o;1",
        "resolution": "1920x1080",
        "dpi": 1600,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "M4", "ultimate": "F" },
        "hardware": { "mouse": "Razer Viper V3 Pro", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/6416950ce6638.png",
        "social": { "twitter": "TenZ", "twitch": "TenZ" }
    },
    {
        "id": 2,
        "name": "Zekken",
        "team": "sentinels",
        "region": "na",
        "agents": ["Raze", "Jett", "Neon"],
        "roles": ["Duelist"],
        "sensitivity": "0.175 @ 1600 DPI",
        "crosshair": "0;c;1;P;t;3;o;1;f;0;m;1;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 1600,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer Viper V3 Pro", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/6416956f0da1e.png",
        "social": { "twitter": "Zekken", "twitch": "Zekken" }
    },
    {
        "id": 3,
        "name": "Sacy",
        "team": "sentinels",
        "region": "na",
        "agents": ["Gekko", "Sova", "Fade"],
        "roles": ["Initiator"],
        "sensitivity": "0.21 @ 800 DPI",
        "crosshair": "0;P;h;0;0t;1;0l;4;0o;1;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Razer Huntsman V3", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/6416954a0788d.png",
        "social": { "twitter": "Sacy", "twitch": "sacy" }
    },
    {
        "id": 4,
        "name": "johnqt",
        "team": "sentinels",
        "region": "na",
        "agents": ["Cypher", "Sentinel"],
        "roles": ["Sentinel", "IGL"],
        "sensitivity": "0.2 @ 1600 DPI",
        "crosshair": "0;P;o;1;d;1;z;3;0b;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 1600,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Lamzu Atlantis", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/6504cd7687834.png",
        "social": { "twitter": "johnqt", "twitch": "johnqt" }
    },
    {
        "id": 5,
        "name": "Zellsis",
        "team": "sentinels",
        "region": "na",
        "agents": ["KAY/O", "Neon"],
        "roles": ["Initiator", "Flex"],
        "sensitivity": "0.25 @ 800 DPI",
        "crosshair": "0;P;c;1;o;1;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Zowie EC2-CW", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/671b20fca8019.png",
        "social": { "twitter": "Zellsis", "twitch": "Zellsis" }
    },
    {
        "id": 6,
        "name": "Boaster",
        "team": "fnatic",
        "region": "eu",
        "agents": ["Omen", "Brimstone", "Astra"],
        "roles": ["Controller", "IGL"],
        "sensitivity": "0.52 @ 400 DPI",
        "crosshair": "0;s;1;P;c;5;o;1;d;1;z;4;0b;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 400,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer Viper V3 Pro", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "Sony INZONE H9" },
        "image": "https://owcdn.net/img/687e2c495dcc6.png",
        "social": { "twitter": "Boaster", "twitch": "Boaster" }
    },
    {
        "id": 7,
        "name": "Derke",
        "team": "vitality",
        "region": "eu",
        "agents": ["Jett", "Raze", "Yoru"],
        "roles": ["Duelist"],
        "sensitivity": "0.74 @ 400 DPI",
        "crosshair": "0;s;1;P;o;1;d;1;z;3;0b;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 400,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Logitech G Pro X TKL", "monitor": "BenQ XL2566K", "headset": "Sony INZONE H9" },
        "image": "https://owcdn.net/img/677d64fd893bb.png",
        "social": { "twitter": "Derke", "twitch": "Derke" }
    },
    {
        "id": 8,
        "name": "Alfajer",
        "team": "fnatic",
        "region": "eu",
        "agents": ["Killjoy", "Cypher", "Viper"],
        "roles": ["Sentinel"],
        "sensitivity": "0.21 @ 800 DPI",
        "crosshair": "0;s;1;P;c;5;o;1;d;1;z;3;0b;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer DeathAdder V3", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "Sony INZONE H9" },
        "image": "https://owcdn.net/img/687e2c40ac175.png",
        "social": { "twitter": "Alfajer", "twitch": "Alfajer" }
    },
    {
        "id": 9,
        "name": "Leo",
        "team": "fnatic",
        "region": "eu",
        "agents": ["Sova", "Fade", "Gekko"],
        "roles": ["Initiator"],
        "sensitivity": "0.36 @ 800 DPI",
        "crosshair": "0;s;1;P;h;0;0l;3;0v;3;0o;0;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "Sony INZONE H9" },
        "image": "https://owcdn.net/img/632c748c9735d.png",
        "social": { "twitter": "Leo", "twitch": "Leo" }
    },
    {
        "id": 10,
        "name": "Chronicle",
        "team": "fnatic",
        "region": "eu",
        "agents": ["Sova", "Viper", "KAY/O"],
        "roles": ["Initiator", "Flex"],
        "sensitivity": "0.33 @ 800 DPI",
        "crosshair": "0;P;c;7;o;1;d;1;z;3;0b;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Lamzu Atlantis Mini", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "Sony INZONE H9" },
        "image": "https://owcdn.net/img/632c74a0050aa.png",
        "social": { "twitter": "Chronicle", "twitch": "Chronicle" }
    },
    {
        "id": 11,
        "name": "cNed",
        "team": "fut",
        "region": "tr",
        "agents": ["Jett", "Raze", "Neon"],
        "roles": ["Duelist"],
        "sensitivity": "0.32 @ 800 DPI",
        "crosshair": "0;P;c;1;u;000000FF;h;0;0l;3;0v;4;0g;1;0o;1;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "G Pro X 2" },
        "image": "https://owcdn.net/img/65dbc5cfc3b28.png",
        "social": { "twitter": "cNed", "twitch": "cNed" }
    },
    {
        "id": 12,
        "name": "Sayf",
        "team": "vitality",
        "region": "eu",
        "agents": ["Raze", "Jett", "Neon"],
        "roles": ["Duelist", "Flex"],
        "sensitivity": "0.31 @ 800 DPI",
        "crosshair": "0;P;c;1;o;1;f;0;0l;3;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "E", "ultimate": "X" },
        "hardware": { "mouse": "Vaxee XE", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/65eb1b28e2198.png",
        "social": { "twitter": "Sayf", "twitch": "Sayf" }
    },
    {
        "id": 13,
        "name": "aspas",
        "team": "leviatan",
        "region": "na",
        "agents": ["Jett", "Raze", "Neon"],
        "roles": ["Duelist"],
        "sensitivity": "0.4 @ 800 DPI",
        "crosshair": "0;P;c;5;h;0;0l;4;0o;0;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "Q", "ability2": "E", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/663e2777426b3.png",
        "social": { "twitter": "aspas", "twitch": "aspas" }
    },
    {
        "id": 14,
        "name": "kiNgg",
        "team": "leviatan",
        "region": "na",
        "agents": ["Viper", "Omen", "Brimstone"],
        "roles": ["Controller", "IGL"],
        "sensitivity": "0.3 @ 800 DPI",
        "crosshair": "0;s;1;P;c;1;o;1;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight", "keyboard": "HyperX Alloy Origins", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/663e279201bd7.png",
        "social": { "twitter": "kiNgg", "twitch": "kiNgg" }
    },
    {
        "id": 15,
        "name": "f0rsakeN",
        "team": "paper-rex",
        "region": "apac",
        "agents": ["Yoru", "KAY/O", "Harbor"],
        "roles": ["Flex", "Duelist"],
        "sensitivity": "0.712 @ 800 DPI",
        "crosshair": "0;s;1;P;o;1;0t;1;0l;1;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud Alpha" },
        "image": "https://owcdn.net/img/67c6ffbd72808.png",
        "social": { "twitter": "f0rsakeN", "twitch": "f0rsakeN" }
    },
    {
        "id": 16,
        "name": "Jinggg",
        "team": "paper-rex",
        "region": "apac",
        "agents": ["Raze", "Sage", "Neon"],
        "roles": ["Duelist"],
        "sensitivity": "0.2 @ 1600 DPI",
        "crosshair": "0;s;1;P;c;1;o;1;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 1600,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer Viper V3 Pro", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/67c701558ae34.png",
        "social": { "twitter": "jinggg", "twitch": "jinggg" }
    },
    {
        "id": 17,
        "name": "Tarik",
        "team": "content-creator",
        "region": "na",
        "agents": ["Jett", "Raze", "Reyna"],
        "roles": ["Duelist"],
        "sensitivity": "0.471 @ 800 DPI",
        "crosshair": "0;P;o;1;d;1;0b;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer Viper V3 Pro", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/603c0053229b6.png",
        "social": { "twitter": "tarik", "twitch": "tarik" }
    },
    {
        "id": 18,
        "name": "Kyedae",
        "team": "content-creator",
        "region": "na",
        "agents": ["Killjoy", "Neon", "Sage"],
        "roles": ["Sentinel", "Duelist"],
        "sensitivity": "0.3 @ 800 DPI",
        "crosshair": "0;P;c;5;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight White", "keyboard": "Higround", "monitor": "BenQ XL2546K", "headset": "HyperX Cloud Mix" },
        "image": "https://unavatar.io/youtube/Kyedae",
        "social": { "twitter": "Kyedae", "twitch": "Kyedae" }
    },
    {
        "id": 19,
        "name": "Rawzu",
        "team": "content-creator",
        "region": "eu",
        "agents": ["Phoenix", "Jett"],
        "roles": ["Duelist"],
        "sensitivity": "0.33 @ 800 DPI",
        "crosshair": "0;P;c;5;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Logitech G Pro X 2", "keyboard": "Wooting 60HE", "monitor": "BenQ ZOWIE XL2566K", "headset": "HyperX Cloud Alpha" },
        "image": "https://unavatar.io/youtube/Rawzu",
        "social": { "twitter": "Rawzu", "twitch": "Rawzu" }
    },
    {
        "id": 20,
        "name": "WestJett",
        "team": "content-creator",
        "region": "na",
        "agents": ["Jett", "Reyna"],
        "roles": ["Duelist"],
        "sensitivity": "0.35 @ 800 DPI",
        "crosshair": "0;P;c;1;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight", "keyboard": "Custom", "monitor": "BenQ XL2546K", "headset": "HyperX Cloud II" },
        "image": "https://unavatar.io/youtube/WestJett",
        "social": { "twitter": "WestJett", "twitch": "WestJett" }
    },
    {
        "id": 21,
        "name": "Grim",
        "team": "content-creator",
        "region": "na",
        "agents": ["Sage"],
        "roles": ["Sentinel"],
        "sensitivity": "0.33 @ 800 DPI",
        "crosshair": "0;P;c;1;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer Viper V2 Pro", "keyboard": "Razer Huntsman Mini", "monitor": "BenQ XL2546K", "headset": "HyperX Cloud II" },
        "image": "https://unavatar.io/youtube/Grim",
        "social": { "twitter": "Grim", "twitch": "Grim" }
    },
    {
        "id": 22,
        "name": "Curry",
        "team": "content-creator",
        "region": "na",
        "agents": ["Jett", "Reyna"],
        "roles": ["Duelist"],
        "sensitivity": "0.32 @ 800 DPI",
        "crosshair": "0;P;h;0;0l;4;0o;0;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/642f278097f37.png",
        "social": { "twitter": "Curry", "twitch": "Curry" }
    },
    {
        "id": 23,
        "name": "Hiko",
        "team": "content-creator",
        "region": "na",
        "agents": ["Sova", "Fade"],
        "roles": ["Initiator"],
        "sensitivity": "0.36 @ 800 DPI",
        "crosshair": "0;P;c;1;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Logitech G Pro X Superlight", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2546K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/603c004278a2e.png",
        "social": { "twitter": "Hiko", "twitch": "Hiko" }
    },
    {
        "id": 24,
        "name": "Ethos",
        "team": "content-creator",
        "region": "na",
        "agents": ["Yoru"],
        "roles": ["Duelist"],
        "sensitivity": "0.23 @ 800 DPI",
        "crosshair": "0;P;h;0;f;0;0l;4;0o;0;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer Viper V2 Pro", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://unavatar.io/youtube/Ethos",
        "social": { "twitter": "Ethos", "twitch": "Ethos" }
    },
    {
        "id": 25,
        "name": "AverageJonas",
        "team": "content-creator",
        "region": "eu",
        "agents": ["Sova"],
        "roles": ["Initiator"],
        "sensitivity": "0.385 @ 800 DPI",
        "crosshair": "0;P;c;1;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Logitech G Pro X Superlight", "keyboard": "Razer BlackWidow", "monitor": "ASUS ROG Swift PG279QM", "headset": "SteelSeries Arctis Pro" },
        "image": "https://yt3.ggpht.com/xaUgb7GNDmupJfudhPxM5c5PMnWFModZtZunfEMGQD3VRYWu0EMD3QyOKgAtsYtK1NY0biZlZw=s176-c-k-c0x00ffffff-no-rj-mo",
        "social": { "twitter": "Average_Jonas", "twitch": "AverageJonas" }
    },
    {
        "id": 26,
        "name": "Kaemi",
        "team": "content-creator",
        "region": "eu",
        "agents": ["Jett", "Raze"],
        "roles": ["Duelist"],
        "sensitivity": "0.314 @ 800 DPI",
        "crosshair": "0;P;c;1;h;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Finalmouse Starlight-12", "keyboard": "Wooting 60HE", "monitor": "BenQ ZOWIE XL2566K", "headset": "Logitech G Pro X 2" },
        "image": "https://unavatar.io/youtube/Kaemi",
        "social": { "twitter": "Kaemi", "twitch": "Kaemi" }
    },
    {
        "id": 27,
        "name": "s0m",
        "team": "content-creator",
        "region": "na",
        "agents": ["Omen", "Controller"],
        "roles": ["Controller"],
        "sensitivity": "0.27 @ 800 DPI",
        "crosshair": "0;P;h;0;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://unavatar.io/youtube/s0mCSGO",
        "social": { "twitter": "s0m", "twitch": "s0m" }
    },
    {
        "id": 28,
        "name": "Demon1",
        "team": "nrg",
        "region": "na",
        "agents": ["Jett", "Brimstone"],
        "roles": ["Duelist", "Controller"],
        "sensitivity": "0.1 @ 1600 DPI",
        "crosshair": "0;s;1;P;o;1;d;1;m;1;0b;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 1600,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/663e2646399c4.png",
        "social": { "twitter": "Demon1", "twitch": "Demon1" }
    },
    {
        "id": 29,
        "name": "Ethan",
        "team": "nrg",
        "region": "na",
        "agents": ["KAY/O", "Skye"],
        "roles": ["Initiator"],
        "sensitivity": "0.34 @ 800 DPI",
        "crosshair": "0;P;c;1;o;1;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer DeathAdder V3 Pro", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/663e262174dcc.png",
        "social": { "twitter": "Ethan", "twitch": "ethan" }
    },
    {
        "id": 30,
        "name": "Asuna",
        "team": "100-thieves",
        "region": "na",
        "agents": ["Raze", "KAY/O"],
        "roles": ["Duelist", "Initiator"],
        "sensitivity": "0.295 @ 1400 DPI",
        "crosshair": "0;p;0;s;1;P;o;1;0t;1;0l;2;0a;1;0f;0;1b;0;A;o;1;d;1;0b;0;1b;0;S;c;0;s;0.64;o;1",
        "resolution": "1920x1080",
        "dpi": 1400,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer DeathAdder V3 Pro", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2546K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/641692800624c.png",
        "social": { "twitter": "Asuna", "twitch": "Asuna" }
    },
    {
        "id": 31,
        "name": "Cryocells",
        "team": "100-thieves",
        "region": "na",
        "agents": ["Jett", "Chamber"],
        "roles": ["Duelist", "Sentinel"],
        "sensitivity": "0.3 @ 800 DPI",
        "crosshair": "0;P;h;0;0l;4;0o;0;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/641692697b003.png",
        "social": { "twitter": "Cryocells", "twitch": "Cryocells" }
    },
    {
        "id": 32,
        "name": "Boostio",
        "team": "100-thieves",
        "region": "na",
        "agents": ["Killjoy", "Cypher"],
        "roles": ["Sentinel", "IGL"],
        "sensitivity": "0.31 @ 800 DPI",
        "crosshair": "0;P;c;5;o;1;d;1;z;1;0b;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/6416923e2af2b.png",
        "social": { "twitter": "Boostio", "twitch": "Boostio" }
    },
    {
        "id": 33,
        "name": "KangKang",
        "team": "edg",
        "region": "cn",
        "agents": ["Jett", "Raze", "Yoru"],
        "roles": ["Duelist"],
        "sensitivity": "0.35 @ 800 DPI",
        "crosshair": "0;s;1;P;c;5;u;000000FF;o;1;d;1;z;1;0b;0;1b;0;S;c;5;s;0.628;o;1",
        "resolution": "1280x960",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/663dcc78393e2.png",
        "social": { "twitter": "ZmjjKK", "twitch": "ZmjjKK" }
    },
    {
        "id": 34,
        "name": "Chichoo",
        "team": "edg",
        "region": "cn",
        "agents": ["Viper", "Omen"],
        "roles": ["Controller"],
        "sensitivity": "0.22 @ 800 DPI",
        "crosshair": "0;P;c;1;h;0;0l;3;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight", "keyboard": "Logitech G Pro X", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/663dccb20c90d.png",
        "social": { "twitter": "Chichoo", "twitch": "Chichoo" }
    },
    {
        "id": 35,
        "name": "Saadhak",
        "team": "loud",
        "region": "br",
        "agents": ["KAY/O", "Gekko"],
        "roles": ["Initiator", "IGL"],
        "sensitivity": "0.24 @ 800 DPI",
        "crosshair": "0;P;c;1;o;1;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "Razer Viper V3 Pro", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/65e9006932e8b.png",
        "social": { "twitter": "Saadhak", "twitch": "Saadhak" }
    },
    {
        "id": 36,
        "name": "Less",
        "team": "loud",
        "region": "br",
        "agents": ["Viper", "Killjoy"],
        "roles": ["Sentinel"],
        "sensitivity": "0.33 @ 800 DPI",
        "crosshair": "0;P;c;1;o;1;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Logitech G Pro X TKL", "monitor": "BenQ XL2566K", "headset": "Logitech G Pro X 2" },
        "image": "https://owcdn.net/img/65e9007e0c707.png",
        "social": { "twitter": "Less", "twitch": "Less" }
    },
    {
        "id": 37,
        "name": "MaKo",
        "team": "drx",
        "region": "kr",
        "agents": ["Omen", "Viper"],
        "roles": ["Controller"],
        "sensitivity": "0.33 @ 800 DPI",
        "crosshair": "0;s;1;P;c;1;o;1;f;0;0l;4;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 800,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight 2", "keyboard": "Wooting 60HE", "monitor": "BenQ XL2566K", "headset": "HyperX Cloud II" },
        "image": "https://owcdn.net/img/65e807df97230.png",
        "social": { "twitter": "MaKo", "twitch": "MaKo" }
    },
    {
        "id": 38,
        "name": "BuZz",
        "team": "drx",
        "region": "kr",
        "agents": ["Jett", "Raze"],
        "roles": ["Duelist"],
        "sensitivity": "0.57 @ 400 DPI",
        "crosshair": "0;P;c;5;o;1;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 400,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight", "keyboard": "Logitech G Pro X", "monitor": "BenQ XL2566K", "headset": "Logitech G Pro X" },
        "image": "https://owcdn.net/img/65e807cd37f40.png",
        "social": { "twitter": "BuZz", "twitch": "BuZz" }
    },
    {
        "id": 39,
        "name": "Feyzullah",
        "team": "dilvuranlar",
        "region": "kr",
        "agents": ["Jett", "Raze"],
        "roles": ["Duelist"],
        "sensitivity": "0.57 @ 400 DPI",
        "crosshair": "0;P;c;5;o;1;f;0;0t;1;0l;2;0o;2;0a;1;0f;0;1b;0",
        "resolution": "1920x1080",
        "dpi": 400,
        "zoom_sensitivity": 1,
        "keybinds": { "ability1": "C", "ability2": "Q", "ultimate": "X" },
        "hardware": { "mouse": "G Pro X Superlight", "keyboard": "Logitech G Pro X", "monitor": "BenQ XL2566K", "headset": "Logitech G Pro X" },
        "image": "https://owcdn.net/img/65e807cd37f40.png",
        "social": { "twitter": "BuZz", "twitch": "BuZz" }
    }
];
module.exports = playersData;